# Generated by Django 5.1.2 on 2024-10-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Name', models.CharField(max_length=20)),
                ('Acc_No', models.IntegerField(primary_key=True, serialize=False)),
                ('Dob', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
            ],
        ),
    ]
